id: P0CBBD9A2
initial_creation_type: input
source_metadata:
  title: Lochen Chönyi Zangmo
  language: en
  description: 'Texts by and about Jetsün Lochen Chönyi Zangmo (lo chen chos nyid
    bzang mo, 1853/1865–1950/1951) of Shukseb (shug gseb), one of the most celebrated
    yoginīs of the last century:'
  volume:
    451082ce810b4dbc943e7b32d290281c:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      parent: Guru Yoga
    2fbee2918206408e82c86aea90817735:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      parent: Long Life Prayers
created_at: '2022-03-01T00:38:09.278318'
last_modified_at: '2022-03-01T00:38:09.278325'
